#### KFold Cross Validation

The goal of ensemble methods is to combine the predictions of several base estimators built with a given learning algorithm in order to improve generalizability / robustness over a single estimator.

In [10]:
from sklearn.linear_model import LogisticRegression as lr
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier as rf
from sklearn.datasets import load_digits
digits=load_digits()

In [14]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(digits.data,digits.target,test_size=0.5)

### Logistic Regression

In [18]:
lr = LogisticRegression(solver='liblinear',multi_class='ovr')
lr.fit(x_train, y_train)
lr.score(x_test, y_test)

0.9588431590656284

### SVM

In [19]:
svm = SVC()
svm.fit(x_train, y_train)
svm.score(x_test, y_test)

0.9844271412680756

### Random Forest

In [20]:
rf = RandomForestClassifier()
rf.fit(x_train, y_train)
rf.score(x_test, y_test)

0.9744160177975528

## KFold cross validation

In [22]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [24]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [25]:
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

In [26]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)

scores_logistic = []
scores_svm = []
scores_rf = []

for train_index, test_index in folds.split(digits.data,digits.target):
    X_train, X_test, y_train, y_test = digits.data[train_index], digits.data[test_index], \
                                       digits.target[train_index], digits.target[test_index]
    scores_logistic.append(get_score(LogisticRegression(solver='liblinear',multi_class='ovr'), X_train, X_test, y_train, y_test))  
    scores_svm.append(get_score(SVC(gamma='auto'), X_train, X_test, y_train, y_test))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators=40), X_train, X_test, y_train, y_test))

In [27]:
scores_logistic

[0.8948247078464107, 0.9532554257095158, 0.9098497495826378]

In [28]:
scores_svm

[0.3806343906510851, 0.41068447412353926, 0.5125208681135225]

In [29]:
scores_rf

[0.9465776293823038, 0.9465776293823038, 0.9365609348914858]

## cross_val_score function  ---> will solve all the above ,not required KFold cross validation

In [33]:
from sklearn.model_selection import cross_val_score

#### Logistic regression model performance using cross_val_score

In [34]:
cross_val_score(LogisticRegression(solver='liblinear',multi_class='ovr'), digits.data, digits.target,cv=3)

array([0.89482471, 0.95325543, 0.90984975])

## svm model performance using cross_val_score

In [38]:
cross_val_score(SVC(),digits.data,digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

## random forest performance using cross_val_score

In [40]:
cross_val_score(RandomForestClassifier(),digits.data,digits.target)

array([0.92777778, 0.91388889, 0.95543175, 0.96935933, 0.91643454])

## Parameter tunning using k fold cross validation

In [43]:
import numpy as np
scores1 = cross_val_score(RandomForestClassifier(n_estimators=10),digits.data, digits.target, cv=10)
np.average(scores1)

0.9154065797641217

In [45]:
scores1 = cross_val_score(RandomForestClassifier(n_estimators=50),digits.data, digits.target, cv=10)
np.average(scores1)

0.9493606455617629

* Here we used cross_val_score to fine tune our random forest classifier and figured that having around 40 trees in random forest gives best result.